# Site settings
title: alba~math
lang: fr
languages: ["fr", "en"]
email: alba@albamath.com
logo: /assets/img/cropped-albamath-shaded-logo-small-uncentered-tinified.png
author: Alba MÁLAGA
show_downloads: false # "true" or "false" to indicate whether to provide a download URL
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://albamath.com" # the base hostname & protocol for the site, e.g. http://example.com
# generate social links in footer (only available in some themes, e.g. minima)
twitter_username: alba_math
github_username:  albamath
# comments
# comments_engine: talkyard
disqus:
  shortname: albamath
talkyard:
  server_url: https://comments-for-albamath-com.talkyard.net
  script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
# theme
theme: minima
minima:
  skin: classic
# Permalink structure
permalink: :path

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

#plugins
plugins:
  - jemoji

#collections
collections:
  publications:
    output: true
    permalink: :path
  objects:
    permalink: :path

# Exclude these files from your production_site
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
