# Site settings
title: alba~math
lang: fr
languages: ["fr", "en"]
email: alba@albamath.com
logo: /assets/img/cropped-albamath-shaded-logo-small-uncentered-tinified.png
author: Alba MÁLAGA
show_downloads: false # "true" or "false" to indicate whether to provide a download URL
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: "" # the subpath of the site, e.g. /blog
url: "http://albamath.com" # the base hostname & protocol for the site, e.g. http://example.com
# generate social links in footer (only available in some themes, e.g. minima)
twitter_username: alba_math
github_username:  albamath
# comments
# comments_engine: talkyard
disqus:
  shortname: albamath
talkyard:
  server_url: https://comments-for-albamath-com.talkyard.net
  script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js
# theme
theme: minima
minima:
  skin: classic
# Permalink structure
permalink: :path

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page
  - scope:
      path: "*/index.md"
      type: pages
    values:
      layout: home
  - scope:
      type: objects
    values:
      layout: page
  - scope:
      type: publications
    values:
      layout: page
  - scope:
      path: "*/feed.xml"
    values:
      layout: feed
  - scope:
      path: fr
    values:
      lang: fr
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: es
    values:
      lang: es
  - scope:
      path: pl
    values:
      lang: pl
  - scope:
      path: "_publications/fr"
      type: publications
    values:
      lang: fr
  - scope:
      path: "_publications/en"
      type: publications
    values:
      lang: en
  - scope:
      path: "_publications/es"
      type: publications
    values:
      lang: es
  - scope:
      path: "_publications/pl"
      type: publications
    values:
      lang: pl
  - scope:
      path: "_objects/fr"
      type: objects
    values:
      lang: fr
  - scope:
      path: "_objects/en"
      type: objects
    values:
      lang: en
  - scope:
      path: "_objects/es"
      type: objects
    values:
      lang: es
  - scope:
      path: "_objects/pl"
      type: objects
    values:
      lang: pl
  - scope:
      path: "_posts/fr"
      type: posts
    values:
      lang: fr
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en
  - scope:
      path: "_posts/es"
      type: posts
    values:
      lang: es
  - scope:
      path: "_posts/pl"
      type: posts
    values:
      lang: pl

#plugins
plugins:
  - jemoji

#collections
collections:
  publications:
    output: true
    permalink: :path
  objects:
    permalink: :path

# Exclude these files from your production_site
exclude: ['README.md', 'Gemfile.lock', 'Gemfile']
