# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
  en: alba~math
  fr: alba~math
email: webmaster@albamath.com
description:
  en: [alba~math](http://albamath.com) contains a bunch of contributions by Alba Marina Málaga Sabogal. You can find here updates in my research, the modules I develop for scientific outreach and a general discussion on math-related issues in plenty of aspects.
  fr: [alba~math](http://albamath.com) contient un ensemble de contributions par Alba Marina Málaga Sabogal. Vous retrouverez ici des nouvelles sur ma recherche, mes efforts de vulgarisation scientifique, et en général sur divers aspects de la vie qui peuvent être discutés mathématiquement.
index:
  en: 
  fr: accueil.html
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://albamath.com" # the base hostname & protocol for your site
github_username:  AMSab

# Build settings
markdown: kramdown
